# Versions for the whole project.

[versions]
kotlin = "1.6.10"
coroutine = "1.5.2"
serialization = "1.3.0"

compose = "1.0.1" # Jetbrains Compose (https://github.com/JetBrains/compose-jb)

androidGradle = "4.2.0"


[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

compose = { id = "org.jetbrains.compose", version.ref = "compose" }


[libraries]
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }

serializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }


# [bundles]
# bundleName = ["a", "b", "c"]
